### ISSUE TITLE
API rate limit exceeded when getting transaction on main net when through api & function  is used   

### ISSUE THREAD

**Issue by huzaifakrptomind** [bnb-chain/javascript-sdk#359]
#When I use through API then this (api/v1/transactions) then  message appear   "message": "API rate limit exceeded"
as eg :  https://testnet-dex.binance.org/api/v1/transactions?address=" path of main-net address "&startTime=1635938169806
as you see at this link --- ( https://docs.binance.org/api-reference/dex-api/paths.html#apiv1transactions ) ---

#When I use through this API and use this ( api/v1/txs )  then this msg appear {
    "code": 500,
    "message": "encoding/hex: invalid byte: U+0073 's'"
}
as eg : (https://dex.binance.org/api/v1/txs?address="--- path of main-net address ---" ) 
as you see at this link  --- https://docs.binance.org/api-reference/dex-api/block-service.html#apiv1txs ---

#When I use through this function ( getTxs ) then this appear "message": "no route and no API found with those values" 
as docs  you see at ---  (https://github.com/bnb-chain/javascript-sdk/blob/master/docs/api-docs/classes/bncclient.md#gettxs )--
#When I use through this  function ( getTransactions ) then this return  only 24 hrs transaction  
as docs you see at  (--- https://github.com/bnb-chain/javascript-sdk/blob/master/docs/api-docs/classes/bncclient.md#getTransactions  ) ---

    I have tried to solve this issue in different ways but still failed

**Comment by danieljcss** [comment]
Notice that the getTxs function is using the API for block service: https://docs.bnbchain.org/docs/beaconchain/develop/api-reference/dex-api/block-service

Therefore, you do not have to initialize your BncClient, since this will ask some node-info, which will fail. Instead, you can do the following:
```js
const { BncClient } = require("@binance-chain/javascript-sdk");
const client = new BncClient("https://api.binance.org");

const transactions = await client.getTxs(address, startTime, endTime);
```
Where `startTime < endTime` are in miliseconds, and `endTime - startTime > 7 days`. See [this](https://github.com/bnb-chain/bnb-chain.github.io/blob/master/docs/beaconchain/develop/api-reference/dex-api/block-service.md#apiv1txs).
